### ISSUE TITLE
how to remove from startup??

### ISSUE THREAD

**Issue by Spidey1337** [Not-Cyrus/Login-Stealer#10]
^^^^^^^^

**Comment by Not-Cyrus** [comment]
Only thing that's added to startup is token logging
`%localappdata%\Discord\app-1.0.9002\modules\discord_modules-1\discord_modules\index.js`
`%localappdata%\DiscordCanary\app-1.0.34\modules\discord_modules-15\discord_modules\index.js`
(thing with ptb it's the same general path)

**Comment by Not-Cyrus** [comment]
Closed due to age
