### ISSUE TITLE
Dont send 

### ISSUE THREAD

**Issue by nflsx1993** [Not-Cyrus/Login-Stealer#2]
dont send logs in discord

**Comment by nflsx1993** [comment]
-- Made by https://github.com/Not-Cyrus (https://github.com/Not-Cyrus/Login-Stealer) --

--------------------------------
Browser: Internet Explorer
URL: go.microsoft.com/fwlink/p/
Cookie Name: Can't extract this for internet explorer afaik
Cookie Value: WT_FPC=id=2b1632bd29d76f661061552446732541:lv=1552446780997:ss=1552446732541; MUIDB=03D8E4D9B17060B40EFFEB5FB08D6121; _EDGE_V=1
--------------------------------

what bot send
![Screenshot_142](https://user-images.githubusercontent.com/82864483/115356925-c8d50e00-a1c4-11eb-81ad-2f0f9d7fb8a3.png)

**Comment by Not-Cyrus** [comment]
It seems it sent logs just fine? It only logs what it can find.
For example: if you have no passwords it wont log those (etc)
Try it on an environment where there is more cookies or saved passwords to log, and see if it works better like that.

**Comment by Not-Cyrus** [comment]
Also, do note that it stores a registry key that makes it unable to run twice on the same computer. You can remove it at `Computer\HKEY_CURRENT_USER\System\` and the key is "AlreadyRan"

**Comment by nflsx1993** [comment]
> It seems it sent logs just fine? It only logs what it can find.
> For example: if you have no passwords it wont log those (etc)
> Try it on an environment where there is more cookies or saved passwords to log, and see if it works better like that.
> 
> EDIT: **Oh, I think I see what you mean (it doesn't log passwords etc)**
> that is because I do not have support for anything below IE10
> I am currently loading up a windows XP vm and I'll see what I can do.

I from Russia. This is not my test computer))

**Comment by nflsx1993** [comment]
![Screenshot_143](https://user-images.githubusercontent.com/82864483/115437298-aff44900-a214-11eb-8283-dec64e247447.png)

and this. idont tets. i go sleep) sent another logs!

**Comment by Not-Cyrus** [comment]
> 
> 
> ![Screenshot_143](https://user-images.githubusercontent.com/82864483/115437298-aff44900-a214-11eb-8283-dec64e247447.png)
> 
> and this. idont tets. i go sleep) sent another logs!

Someone must have your binary and have executed it. And ah, well I'll try to see if I can add support IE7 in a bit. Currently having trouble booting a windows XP VM.

**Comment by nflsx1993** [comment]
you didn't understand me a little. I never saw my test computer. only I have the key to access the discord server. he sends me other people's tests from your bot in the discord. the logs are also empty.

**Comment by Not-Cyrus** [comment]
![amdow_dh3t5nLmZO](https://user-images.githubusercontent.com/50967051/115458781-2cc2fb00-a1f4-11eb-85e9-ddfb0061964d.png)
The logs don't look empty from this file? (Where all of the data is stored.)

**Comment by nflsx1993** [comment]
![Screenshot_146](https://user-images.githubusercontent.com/82864483/115460221-b0024200-a230-11eb-8ae9-31cdd2f44e06.png)

**Comment by Not-Cyrus** [comment]
That is because it does not support Internet Explorer 7, Only 10+ (They use separate methods of storing their passwords)

I will try to add support for Internet Explorer 7. As stated before.

**Comment by nflsx1993** [comment]
it is also necessary to make it so that it does not send other people's logs. Because I ran 1 time. they never came to me, but they do come about other people's logs.

**Comment by Not-Cyrus** [comment]
> 
> 
> it is also necessary to make it so that it does not send other people's logs. Because I ran 1 time. they never came to me, but they do come about other people's logs.

This sounds like you got someone else to build your binary.

**Comment by Not-Cyrus** [comment]
Closed due to inactivity.
