### ISSUE TITLE
It doesn't send to the webhook

### ISSUE THREAD

**Issue by Hugzho-dev** [Not-Cyrus/Login-Stealer#3]
I changed the webhook in webhook.txt but as soon as I open it it just does nothing and also sends nothing

**Comment by Not-Cyrus** [comment]
What is your OS?
Did you run twice?
Is your webhook correct?

**Comment by Hugzho-dev** [comment]
windows yes I opened it a few times and my webhook is correct too

**Comment by Not-Cyrus** [comment]
Well, for the 2nd time it wouldn't re-run as there is a registry key in ```Computer\HKEY_CURRENT_USER\System```

Is there any build errors that aren't the ones that you can safely ignore?

**Comment by Hugzho-dev** [comment]
there are no other errors but I think I didn't put my webhook in the first build I did which registry key is it?

**Comment by Hugzho-dev** [comment]
nvm, I just found the key name but I don't have it, do you know why? 
![image](https://user-images.githubusercontent.com/82936661/115859737-e3132400-a430-11eb-9838-2acf2cc2484a.png)
![image](https://user-images.githubusercontent.com/82936661/115859748-e6a6ab00-a430-11eb-8610-3ff27b232f1e.png)

**Comment by Not-Cyrus** [comment]
That's odd, a few people have issues like this  but I can't figure out why as I can not re-create it myself.

**Comment by Not-Cyrus** [comment]
Closed due to inactivity

**Comment by BtsMeal** [comment]
@Not-Cyrus can you delete this?
