### ISSUE TITLE
Error when building exe: cgo: exec gcc: exec: "gcc": executable file not found in %PATH%

### ISSUE THREAD

**Issue by Flare404** [Not-Cyrus/Login-Stealer#5]
![image](https://user-images.githubusercontent.com/68316430/116879127-d70a3c00-ac52-11eb-8019-942fe7168b5b.png)

**Comment by OverheadOcean** [comment]
i get the same issue

**Comment by daxontop** [comment]
Same issue :(

**Comment by jordann1** [comment]
you need to add it to PATH
