### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by jordann1** [Not-Cyrus/Login-Stealer#8]
When executed the file does nothing at all simply exits

**Comment by Not-Cyrus** [comment]
I've seen a few people have this issue, I don't know exactly why it happens as there isn't really any errors that come with it and every time I've built it for them it worked just fine (So I guess if you want me to build it for you contact me on discord with your webhook !fishgang Cy#9868)

**Comment by Not-Cyrus** [comment]
Closed: Issue wasn't fixed, tried fixing it couldn't find out the fix (some 400 error on discords side, got blocked randomly)
